Repository wafflestudio/gatgu-client, pull requests merged in 2021-08, with the labels that each got.

#285 Time/#284
  src/components/ArticleBox/index.tsx
  src/components/WriteArticle/DueDate/DueDate.tsx
  src/helpers/functions/index.ts
  src/helpers/functions/time.ts
  src/screens/ArticleStack/Article/ArticleHeader.tsx
  src/screens/ArticleStack/Article/index.tsx
  src/types/article.ts
Labels: enhancement, sprint

#287 Article report/#286
  src/apis/ArticleApi.ts
  src/components/ReportModal/ReportModal.tsx
  src/components/index.ts
  src/constants/article.ts
  src/helpers/hooks/index.ts
  src/helpers/hooks/useToaster.ts
  src/screens/ArticleStack/DrawerContent/index.tsx
  tsconfig.json
Labels: enhancement, sprint

#289 Article image viewer
  ios/Podfile.lock
  package-lock.json
  package.json
  src/screens/ArticleStack/Article/ProductImages.tsx
  tsconfig.json
Labels: enhancement, sprint

#282 Make chat2/#262
  src/apis/ChatApi.ts
  src/components/WriteArticle/DueDate/DueDate.tsx
  src/enums/chatting.ts
  src/screens/ArticleStack/Article/ProfileChat.tsx
  src/screens/ChattingListStack/ChattingList/index.tsx
  src/screens/ChattingRoomStack/ChatsContainer/ChatBox/index.tsx
  src/screens/ChattingRoomStack/ChatsContainer/index.tsx
  src/screens/ChattingRoomStack/ChattingRoomTemplate.tsx
  src/screens/ChattingRoomStack/Drawer/index.tsx
  src/store/articleSlice/index.ts
  src/store/chatSlice/index.ts
  src/types/chat.ts
  src/types/user.ts
Labels: enhancement

#292 Cursor flat list/#291
  src/components/CursorFlatList/CursorFlatList.tsx
  src/helpers/hooks/useCursorPagination.ts
  src/screens/HomeStack/Home/index.tsx
  src/screens/SearchStack/Search/Search.tsx
Labels: enhancement, sprint

#290 Make chat4/#262
  ios/Podfile.lock
  src/apis/ChatApi.ts
  src/components/InfoContainer/InfoContainer.style.ts
  src/components/Thumbnail/Thumbnail.style.ts
  src/components/Thumbnail/Thumbnail.tsx
  src/components/WriteArticle/AddImage/AddImage.tsx
  src/enums/index.ts
  src/enums/participantStatus.ts
  src/helpers/GatguWebsocket/_internal/BaseWebsocket.ts
  src/helpers/GatguWebsocket/_internal/Provider.tsx
  src/helpers/GatguWebsocket/_internal/types.ts
  src/helpers/hooks/useImageUpload.ts
  src/screens/ArticleStack/Article/ProfileChat.tsx
  src/screens/ChattingListStack/ChattingList/ChattingBox/ChattingBox.style.ts
  src/screens/ChattingListStack/ChattingList/ChattingBox/index.tsx
  src/screens/ChattingListStack/ChattingList/index.tsx
  src/screens/ChattingRoomStack/ChatsContainer/ChatBox/ChatBox.style.tsx
  src/screens/ChattingRoomStack/ChatsContainer/ChatBox/index.tsx
  src/screens/ChattingRoomStack/ChatsContainer/InputBar/InputBar.style.tsx
  src/screens/ChattingRoomStack/ChatsContainer/InputBar/index.tsx
  src/screens/ChattingRoomStack/ChatsContainer/index.tsx
  src/screens/ChattingRoomStack/Drawer/Drawer.style.ts
  src/screens/ChattingRoomStack/Drawer/Modal.tsx
  src/screens/ChattingRoomStack/Drawer/index.tsx
  src/store/chatSlice/index.ts
  src/types/chat.ts
  src/types/user.ts
Labels: enhancement

#297 Refactor code - lint fix + userQuery
  src/App.router.tsx
  src/helpers/hooks/api/index.ts
  src/helpers/hooks/api/userQuery.ts
  src/screens/ArticleStack/Article/ProfileChat.tsx
  src/screens/ArticleStack/DrawerContent/index.tsx
  src/screens/ChattingListStack/ChattingList/index.tsx
  src/screens/ChattingRoomStack/ChatsContainer/index.tsx
  src/screens/ChattingRoomStack/Drawer/index.tsx
  src/screens/UserStack/Profile/index.tsx
  src/screens/UserStack/ProfileModify/index.tsx
  src/store/chatSlice/index.ts
Labels: refactorize

#298 Article fix + lint
  src/App.router.tsx
  src/components/AppLoading/index.tsx
  src/components/WriteArticle/AddImage/AddImage.style.ts
  src/components/WriteArticle/AddImage/AddImage.tsx
  src/components/WriteArticle/Recruiting/Recruiting.tsx
  src/components/WriteArticle/index.tsx
  src/helpers/GatguWebsocket/_internal/Provider.tsx
  src/helpers/hooks/useCursorPagination.ts
  src/helpers/hooks/useImageUpload.ts
  src/screens/ArticleStack/Article/ProfileChat.tsx
  src/screens/ArticleStack/DrawerContent/index.tsx
  src/screens/AuthStack/Login/index.tsx
  src/screens/ChattingListStack/ChattingList/ChattingBox/index.tsx
  src/screens/ChattingListStack/ChattingList/index.tsx
  src/screens/ChattingRoomStack/ChatsContainer/ChatBox/index.tsx
  src/screens/ChattingRoomStack/ChatsContainer/InputBar/InputBar.style.tsx
  src/screens/ChattingRoomStack/ChatsContainer/InputBar/index.tsx
  src/screens/ChattingRoomStack/ChatsContainer/index.tsx
  src/screens/ChattingRoomStack/ChattingRoomStack.tsx
  src/screens/ChattingRoomStack/ChattingRoomTemplate.tsx
  src/screens/ChattingRoomStack/Drawer/index.tsx
  src/types/article.ts
Labels: bug

#296 Design system/#295
  package-lock.json
  package.json
  src/components/CursorFlatList/CursorFlatList.tsx
  src/components/Gatgu/GButton/GButton.styled.ts
  src/components/Gatgu/GButton/GButton.tsx
  src/components/Gatgu/GButton/index.ts
  src/components/Gatgu/GIconButton/GIconButton.styled.tsx
  src/components/Gatgu/GIconButton/GIconButton.tsx
  src/components/Gatgu/GInput/GInput.styled.ts
  src/components/Gatgu/GInput/GInput.tsx
  src/components/Gatgu/GInput/index.ts
  src/components/Gatgu/GSpace/GSpace.tsx
  src/components/Gatgu/GSpace/index.ts
  src/components/Gatgu/GText/GText.styled.ts
  src/components/Gatgu/GText/GText.tsx
  src/components/Gatgu/GText/index.ts
  src/components/Gatgu/index.ts
  src/components/ReportModal/ReportModal.tsx
  src/components/WriteArticle/DueDate/DueDate.tsx
  src/components/WriteArticle/index.tsx
  src/screens/ArticleStack/Article/ProfileChat.tsx
  src/screens/ArticleStack/DrawerContent/Drawer.style.ts
  src/screens/ArticleStack/DrawerContent/index.tsx
  src/screens/AuthStack/Login/index.tsx
  src/screens/AuthStack/ServiceTerms/index.tsx
  src/screens/SearchStack/Search/Search.tsx
  src/screens/UserStack/Profile/Logged/HistoryList.style.ts
  src/screens/UserStack/Profile/Logged/HistoryList.tsx
  src/screens/UserStack/Profile/Profile.style.ts
  src/screens/UserStack/Profile/UnLogged/UnLogged.style.ts
  src/screens/UserStack/Profile/UnLogged/index.tsx
  src/screens/UserStack/Profile/index.tsx
  src/screens/UserStack/ProfileModify/index.tsx
  src/screens/UserStack/components/FootTerms/FootTerms.style.ts
  src/screens/UserStack/components/FootTerms/index.tsx
  src/types/shared.ts
Labels: enhancement, sprint

#303 글쓰기 수정 픽스
  src/apis/ArticleApi.ts
  src/components/WriteArticle/AddImage/AddImage.style.ts
  src/components/WriteArticle/AddImage/AddImage.tsx
  src/components/WriteArticle/index.tsx
  src/helpers/hooks/useImageUpload.ts
Labels: hotfix

#301 Configs/#300
  ios/Podfile.lock
  package-lock.json
  src/App.router.tsx
  src/assets/splash/android/drawable-hdpi/같구로고-13.png
  src/assets/splash/android/drawable-mdpi/같구로고-13.png
  src/assets/splash/android/drawable-xhdpi/같구로고-13.png
  src/assets/splash/android/drawable-xxhdpi/같구로고-13.png
  src/assets/splash/android/drawable-xxxhdpi/같구로고-13.png
  src/assets/splash/ios/같구로고-13.png
  src/assets/splash/ios/같구로고-13@2x.png
  src/assets/splash/ios/같구로고-13@3x.png
  src/components/Gatgu/GButton/GButton.styled.ts
  src/components/Gatgu/GButton/GButton.tsx
  src/helpers/functions/navigation.tsx
  src/helpers/functions/time.ts
  src/screens/AuthStack/AuthStack.tsx
  src/screens/ChattingListStack/ChattingListStack.tsx
  src/screens/HomeStack/HomeStack.tsx
  src/screens/SearchStack/SearchStack.tsx
  src/screens/UserStack/Configs/Configs.tsx
  src/screens/UserStack/Configs/index.ts
  src/screens/UserStack/Profile/Logged/Information.tsx
  src/screens/UserStack/Profile/index.tsx
  src/screens/UserStack/UserStack.tsx
  src/screens/UserStack/components/ConfigLayout/ConfigLayout.tsx
  src/screens/UserStack/components/ConfigLayout/index.ts
  src/screens/UserStack/components/LogoutModal/LogoutModal.tsx
  src/screens/UserStack/components/LogoutModal/index.ts
  src/screens/WriteArticleStack/WriteArticleStack.tsx
Labels: enhancement, sprint

#294 Make chat5/#262 (pagination and image upload issues and minor design issues)
  src/apis/ArticleApi.ts
  src/apis/ChatApi.ts
  src/components/CursorFlatList/CursorFlatList.tsx
  src/components/WriteArticle/index.tsx
  src/helpers/GatguWebsocket/_internal/BaseWebsocket.ts
  src/helpers/GatguWebsocket/_internal/Provider.tsx
  src/helpers/GatguWebsocket/_internal/types.ts
  src/helpers/functions/time.ts
  src/helpers/hooks/useCursorPagination.ts
  src/screens/ArticleStack/Article/ProfileChat.tsx
  src/screens/ChattingListStack/ChattingList/ChattingBox/index.tsx
  src/screens/ChattingListStack/ChattingList/index.tsx
  src/screens/ChattingRoomStack/ChatsContainer/ChatBox/index.tsx
  src/screens/ChattingRoomStack/ChatsContainer/index.tsx
  src/screens/ChattingRoomStack/ChattingRoomStack.tsx
  src/screens/ChattingRoomStack/Drawer/Drawer.style.ts
  src/screens/ChattingRoomStack/Drawer/index.tsx
  src/types/chat.ts
Labels: enhancement

#309 Authorization/#308
  src/App.router.tsx
  src/components/UnAuthorizedModal/UnAuthorizedModal.tsx
  src/components/UnAuthorizedModal/index.ts
  src/components/WriteArticle/index.tsx
  src/helpers/bootstrap/hooks/useAutoLogin.ts
  src/helpers/routes.ts
  src/screens/ArticleStack/Article/ProfileChat.tsx
  src/screens/ArticleStack/Article/index.tsx
  src/screens/ArticleStack/ArticleStack.tsx
  src/screens/AuthStack/AuthStack.tsx
  src/screens/ChattingListStack/ChattingListStack.tsx
  src/screens/MainTabs/index.tsx
  src/screens/UserStack/Configs/Configs.tsx
  src/screens/UserStack/Login/Login.style.ts
  src/screens/UserStack/Login/index.tsx
  src/screens/UserStack/Profile/UnLogged/index.tsx
  src/screens/UserStack/Profile/index.tsx
  src/screens/UserStack/ServiceTerms/TOS.style.ts
  src/screens/UserStack/ServiceTerms/content.ts
  src/screens/UserStack/ServiceTerms/index.tsx
  src/screens/UserStack/SignUp/Check.style.ts
  src/screens/UserStack/SignUp/Check.tsx
  src/screens/UserStack/SignUp/Input.style.ts
  src/screens/UserStack/SignUp/Input.tsx
  src/screens/UserStack/SignUp/SignUp.style.ts
  src/screens/UserStack/SignUp/index.tsx
  src/screens/UserStack/UserStack.tsx
  src/screens/WriteArticleStack/WriteArticleStack.tsx
  src/store/userSlice/userSlice.ts
Labels: enhancement

#318 Feat/#317
  src/apis/ArticleApi.ts
  src/components/ArticleBox/ArticleBox.style.ts
  src/components/ArticleBox/ArticleBoxShimmer.tsx
  src/components/ArticleBox/index.tsx
  src/components/Empty/EmptyTemplate.tsx
  src/components/Empty/EmptyTemplateBody.tsx
  src/components/Empty/index.ts
  src/components/Error/index.tsx
  src/components/Shimmer/HomeShimmer.tsx
  src/components/index.ts
  src/helpers/hooks/useCursorPagination.ts
  src/screens/ArticleStack/Article/ProductImages.tsx
  src/screens/ArticleStack/Article/ProfileChat.tsx
  src/screens/ArticleStack/Article/index.tsx
  src/screens/ArticleStack/DrawerContent/index.tsx
  src/screens/HomeStack/Home/index.tsx
  src/screens/SearchStack/Search/Search.tsx
  src/screens/UserStack/Profile/Logged/Force.tsx
  src/screens/UserStack/UserGatgu/UserGatgu.tsx
  src/screens/UserStack/UserGatgu/UserGatguList.tsx
  src/screens/UserStack/components/UserGatguEmpty/UserGatguEmpty.tsx
Labels: enhancement

#312 Profile image 수정하기 되게 만들기
  src/apis/UserApi.ts
  src/helpers/hooks/usePickImage.ts
  src/screens/ChattingListStack/ChattingList/index.tsx
  src/screens/UserStack/ProfileModify/ProfileModify.styles.ts
  src/screens/UserStack/ProfileModify/index.tsx
Labels: enhancement

#322 Article/#321
  src/apis/ArticleApi.ts
  src/components/Header/Header.style.ts
  src/components/Header/HeaderBackButton.tsx
  src/components/Header/index.tsx
  src/helpers/functions/navigation.tsx
  src/screens/ArticleStack/Article/ArticleHeader.tsx
  src/screens/ArticleStack/Article/index.tsx
  src/screens/ArticleStack/DrawerContent/index.tsx
Labels: enhancement

#325 Write art design fix
  src/components/ProfileBox/index.tsx
  src/components/WriteArticle/AddImage/AddImage.tsx
  src/components/WriteArticle/Description/Description.tsx
  src/components/WriteArticle/DueDate/DueDate.style.ts
  src/components/WriteArticle/DueDate/DueDate.tsx
  src/components/WriteArticle/Recruiting/Recruiting.tsx
  src/components/WriteArticle/WriteArticle.style.ts
  src/components/WriteArticle/index.tsx
  src/screens/ArticleStack/Article/ProfileChat.tsx
  src/store/articleSlice/index.ts
  src/types/article.ts
  src/types/user.ts
Labels: design

#316 Error and loading 처리
  ios/Podfile.lock
  src/App.router.tsx
  src/components/Error/index.tsx
  src/components/WriteArticle/AddImage/AddImage.style.ts
  src/components/WriteArticle/AddImage/AddImage.tsx
  src/components/WriteArticle/Description/Description.tsx
  src/components/WriteArticle/DueDate/DueDate.tsx
  src/components/WriteArticle/Link/Link.tsx
  src/components/WriteArticle/Location/Location.tsx
  src/components/WriteArticle/Recruiting/Recruiting.tsx
  src/components/WriteArticle/Title/Title.tsx
  src/components/WriteArticle/WriteArticle.style.ts
  src/components/WriteArticle/index.tsx
  src/helpers/functions/createError.tsx
  src/helpers/functions/index.ts
  src/screens/ArticleStack/Article/ArticleShimmer/ArticleShimmer.style.ts
  src/screens/ArticleStack/Article/ArticleShimmer/ArticleShimmer.tsx
  src/screens/ArticleStack/Article/ProfileChat.tsx
  src/screens/ArticleStack/Article/index.tsx
  src/screens/ArticleStack/DrawerContent/index.tsx
  src/screens/ChattingListStack/ChattingList/ChattingListShimmer/ChattingListShimmer.tsx
  src/screens/ChattingListStack/ChattingList/index.tsx
  src/screens/ChattingRoomStack/ChatsContainer/InputBar/index.tsx
  src/screens/ChattingRoomStack/Drawer/Modal.tsx
  src/screens/ChattingRoomStack/Drawer/index.tsx
  src/screens/SearchStack/hooks/useRecentSearch.ts
  src/screens/UserStack/Login/index.tsx
  src/screens/UserStack/ProfileModify/index.tsx
  src/screens/UserStack/SignUp/index.tsx
  src/store/chatSlice/index.ts
Labels: design

#332 Article/#331
  android/app/build.gradle
  android/app/src/main/java/com/gatgu/ios/MainActivity.java
  android/app/src/main/java/com/gatgu/ios/MainApplication.java
  android/app/src/main/res/drawable/launch_screen.png
  android/app/src/main/res/layout/launch_screen.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/values/colors.xml
  android/settings.gradle
  package-lock.json
  package.json
  src/components/WriteArticle/AddImage/AddImage.style.ts
  src/components/WriteArticle/AddImage/AddImage.tsx
  src/components/WriteArticle/DueDate/DueDate.tsx
  src/components/WriteArticle/Recruiting/Recruiting.tsx
  src/components/WriteArticle/index.tsx
  src/constants/navigateOption.ts
  src/helpers/bootstrap/App.bootstrap.tsx
  src/helpers/functions/time.ts
  src/helpers/hooks/useCursorPagination.ts
  src/helpers/hooks/useToaster.ts
  src/helpers/hooks/useToaster.tsx
  src/screens/ArticleStack/Article/index.tsx
  src/screens/ArticleStack/ArticleStack.tsx
  src/screens/ArticleStack/DrawerContent/Drawer.style.ts
  src/screens/ArticleStack/DrawerContent/index.tsx
  src/screens/HomeStack/Home/index.tsx
  src/screens/HomeStack/HomeStack.tsx
  src/screens/UserStack/Profile/index.tsx
  src/screens/UserStack/UserGatgu/UserGatgu.tsx
  src/types/shared.ts
Labels: bug, design
