Repository wafflestudio/gatgu-client, pull requests merged in 2021-07, with the labels that each got.

#256 article create 안 되게 수정
  src/apis/ArticleApi.ts
  src/components/WriteArticle/index.tsx
  src/store/articleSlice/index.ts
  src/types/article.ts
Labels: hotfix

#257 search page refactor
  App.tsx
  package-lock.json
  package.json
  src/apis/ArticleApi.ts
  src/assets/images/empty.png
  src/components/ArticleBox/index.tsx
  src/components/Button/index.tsx
  src/components/CheckBox/index.tsx
  src/components/CursorFlatList/CursorFlatList.tsx
  src/components/Thumbnail/index.tsx
  src/components/index.ts
  src/helpers/functions/asyncStorage.ts
  src/helpers/hooks/index.ts
  src/helpers/hooks/useCursorPagination.ts
  src/helpers/hooks/useKeywordDispatch.ts
  src/screens/HomeStack/Home/index.tsx
  src/screens/SearchStack/Search.style.ts
  src/screens/SearchStack/Search/Search.tsx
  src/screens/SearchStack/Search/index.ts
  src/screens/SearchStack/SearchBar/SearchBar.style.ts
  src/screens/SearchStack/SearchBar/index.tsx
  src/screens/SearchStack/SearchSection/RecentSearch/index.tsx
  src/screens/SearchStack/SearchSection/index.tsx
  src/screens/SearchStack/SearchStack.tsx
  src/screens/SearchStack/SearchedArticle/SearchedList/index.tsx
  src/screens/SearchStack/SearchedArticle/index.tsx
  src/screens/SearchStack/components/RecentSearch/RecentSearch.style.ts
  src/screens/SearchStack/components/RecentSearch/index.tsx
  src/screens/SearchStack/components/SearchResultEmpty/SearchResultEmpty.tsx
  src/screens/SearchStack/components/SearchResultEmpty/index.ts
  src/screens/SearchStack/hooks/useRecentSearch.ts
  src/screens/SearchStack/index.tsx
  src/screens/UserStack/UserGatgu/UserGatguList.tsx
  src/store/index.ts
  src/store/searchSlice/index.ts
Labels: enhancement, refactorize, sprint

#259 Websocket/#258
  App.tsx
  package-lock.json
  package.json
  src/App.router.tsx
  src/helpers/GatguWebsocket/GatguWebsocket.ts
  src/helpers/GatguWebsocket/_internal/BaseWebsocket.ts
  src/helpers/GatguWebsocket/_internal/Provider.tsx
  src/helpers/GatguWebsocket/_internal/getUseInit.ts
  src/helpers/GatguWebsocket/_internal/getUseMessage.ts
  src/helpers/GatguWebsocket/_internal/types.ts
  src/helpers/GatguWebsocket/index.ts
  src/helpers/hooks/useImageUpload.ts
  src/screens/ChattingListStack/ChattingList/index.tsx
  src/screens/ChattingRoomStack/ChatsContainer/InputBar/index.tsx
  src/screens/ChattingRoomStack/ChatsContainer/index.tsx
  src/screens/ChattingRoomStack/ChattingRoomStack.tsx
  src/screens/ChattingRoomStack/ChattingRoomTemplate.tsx
  src/screens/ChattingRoomStack/mockChat.ts
Labels: enhancement, sprint

#260 이미지 업로드에 관해서 수정
  ios/Podfile.lock
  src/apis/ArticleApi.ts
  src/components/WriteArticle/AddImage/AddImage.tsx
  src/components/WriteArticle/DueDate/DueDate.style.ts
  src/components/WriteArticle/DueDate/DueDate.tsx
  src/components/WriteArticle/index.tsx
  src/helpers/hooks/useImageUpload.ts
  src/helpers/hooks/usePickImage.ts
  src/screens/ArticleStack/Article/index.tsx
  src/screens/HomeStack/HomeStack.tsx
  src/store/articleSlice/index.ts
  src/types/article.ts
  src/types/shared.ts
Labels: enhancement, hotfix, sprint

#271 Auto login/#270
  App.tsx
  src/assets/icons/menu/index.ts
  src/assets/icons/menu/menu.svg
  src/constants/asyncStorage.ts
  src/helpers/bootstrap/App.bootstrap.tsx
  src/helpers/bootstrap/hooks/index.ts
  src/helpers/bootstrap/hooks/useAutoLogin.ts
  src/helpers/functions/asyncStorage.ts
  src/helpers/hooks/useImageUpload.ts
  src/screens/AuthStack/Login/index.tsx
  src/screens/UserStack/Profile/index.tsx
  src/types/asyncStorage.ts
Labels: enhancement, refactorize, sprint

#272 Article 디자인 + 기획 바뀐 부분 수정
  src/assets/images/defaultProfile.png
  src/components/ArticleBox/ArticleBox.style.ts
  src/components/ArticleBox/index.tsx
  src/components/HDRBackBtn/HDRBackBtn.style.ts
  src/components/HDRBackBtn/index.tsx
  src/components/Header/Header.style.ts
  src/components/Header/index.tsx
  src/components/ProfileBox/index.tsx
  src/components/index.ts
  src/constants/article.ts
  src/screens/ArticleStack/Article/ArticleHeader.style.ts
  src/screens/ArticleStack/Article/ArticleHeader.tsx
  src/screens/ArticleStack/Article/Chat.style.ts
  src/screens/ArticleStack/Article/Chat.tsx
  src/screens/ArticleStack/Article/Desc.style.ts
  src/screens/ArticleStack/Article/Desc.tsx
  src/screens/ArticleStack/Article/GoalTopBubble/GoalTopBubble.style.ts
  src/screens/ArticleStack/Article/GoalTopBubble/TopBubble/TopBubble.style.ts
  src/screens/ArticleStack/Article/GoalTopBubble/TopBubble/index.tsx
  src/screens/ArticleStack/Article/GoalTopBubble/index.tsx
  src/screens/ArticleStack/Article/Info.style.ts
  src/screens/ArticleStack/Article/Info.tsx
  src/screens/ArticleStack/Article/ProductImages.tsx
  src/screens/ArticleStack/Article/ProfileChat.style.ts
  src/screens/ArticleStack/Article/ProfileChat.tsx
  src/screens/ArticleStack/Article/Title.style.ts
  src/screens/ArticleStack/Article/Title.tsx
  src/screens/ArticleStack/Article/TitleInfo.style.ts
  src/screens/ArticleStack/Article/TitleInfo.tsx
  src/screens/ArticleStack/Article/index.tsx
  src/screens/ArticleStack/ArticleStack.tsx
  src/screens/ArticleStack/DrawerContent/Drawer.style.ts
  src/screens/ArticleStack/DrawerContent/index.tsx
  src/screens/ChattingRoomStack/ChattingRoomStack.tsx
  src/screens/ChattingRoomStack/ChattingRoomTemplate.tsx
  src/screens/HomeStack/HomeStack.tsx
  src/screens/UserStack/Profile/Logged/index.tsx
  src/screens/UserStack/Profile/UnLogged/index.tsx
  src/screens/UserStack/components/FootTerms/FootTerms.style.ts
  src/screens/UserStack/components/FootTerms/index.tsx
  src/store/articleSlice/index.ts
  src/styles/size.ts
  src/types/article.ts
  src/types/chat.ts
Labels: refactorize, sprint

#279 Design/#278
  package-lock.json
  package.json
  src/assets/icons/BackIcon/BackIcon.svg
  src/assets/icons/Notification/notification.svg
  src/components/Header/Header.style.ts
  src/components/WriteArticle/DueDate/DueDate.tsx
  src/components/WriteArticle/Recruiting/Recruiting.style.ts
  src/components/WriteArticle/Recruiting/Recruiting.tsx
  src/components/WriteArticle/index.tsx
  src/screens/AuthStack/AuthStack.tsx
  src/screens/ChattingListStack/ChattingListStack.tsx
  src/screens/HomeStack/Home/index.tsx
  src/screens/HomeStack/HomeStack.tsx
  src/screens/HomeStack/Notification/NotificationBox/index.tsx
  src/screens/HomeStack/Notification/index.tsx
  src/screens/SearchStack/SearchStack.tsx
  src/screens/UserStack/Profile/Logged/Force.style.ts
  src/screens/UserStack/Profile/Logged/Force.tsx
  src/screens/UserStack/Profile/Logged/Grade.style.ts
  src/screens/UserStack/Profile/Logged/HistoryList.style.ts
  src/screens/UserStack/Profile/Logged/Information.style.ts
  src/screens/UserStack/Profile/Logged/Information.tsx
  src/screens/UserStack/Profile/Logged/index.tsx
  src/screens/UserStack/Profile/index.tsx
  src/screens/UserStack/UserStack.tsx
  src/screens/WriteArticleStack/WriteArticleStack.tsx
Labels: enhancement

#277 Appcenter/#276
  android/app/src/main/assets/appcenter-config.json
  android/app/src/main/res/values/strings.xml
  ios/Podfile.lock
  ios/gatgu/AppCenter-Config.plist
  ios/gatgu/AppDelegate.m
  package-lock.json
  package.json
Labels: enhancement

#275 chatting...
  ios/Podfile.lock
  package-lock.json
  package.json
  src/App.router.tsx
  src/apis/ArticleApi.ts
  src/apis/ChatApi.ts
  src/components/WriteArticle/AddImage/AddImage.tsx
  src/components/WriteArticle/index.tsx
  src/constants/image.ts
  src/enums/chatting.ts
  src/enums/image.ts
  src/enums/index.ts
  src/helpers/GatguWebsocket/_internal/BaseWebsocket.ts
  src/helpers/GatguWebsocket/_internal/Provider.tsx
  src/helpers/GatguWebsocket/_internal/getUseInit.ts
  src/helpers/GatguWebsocket/_internal/types.ts
  src/helpers/functions/time.ts
  src/helpers/hooks/useImageUpload.ts
  src/helpers/hooks/usePickImage.ts
  src/screens/ChattingRoomStack/ChatsContainer/ChatBox/index.tsx
  src/screens/ChattingRoomStack/ChatsContainer/InputBar/InputBar.style.tsx
  src/screens/ChattingRoomStack/ChatsContainer/InputBar/index.tsx
  src/screens/ChattingRoomStack/ChatsContainer/index.tsx
  src/screens/ChattingRoomStack/ChattingRoomStack.tsx
  src/screens/ChattingRoomStack/ChattingRoomTemplate.tsx
  src/screens/ChattingRoomStack/Drawer/index.tsx
  src/types/chat.ts
Labels: enhancement
