Repository wafflestudio/gatgu-client, pull requests merged in 2021-05, with the labels that each got.

#193 edit, article detail, create 로딩 화면 구현
  src/apis/ArticleApi.ts
  src/components/WriteArticle/Recruiting/Recruiting.tsx
  src/components/WriteArticle/index.tsx
  src/helpers/functions/validate.ts
  src/screens/Article/index.tsx
  src/screens/ChattingRoom/Drawer/index.tsx
  src/screens/ChattingRoom/index.tsx
  src/screens/Drawer/index.tsx
  src/screens/WriteArticle/DueDate/DueDate.tsx
  src/store/articleSlice/index.ts
  src/store/chatSlice/index.ts
Labels: enhancement

#195 change app bundle id
  android/app/BUCK
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/gatgu/ios/MainActivity.java
  android/app/src/main/java/com/gatgu/ios/MainApplication.java
  android/app/src/main/java/com/gatgu/ios/generated/BasePackageList.java
  android/build.gradle
  app.json
  ios/Podfile.lock
  ios/gatgu.xcodeproj/project.pbxproj
  ios/gatgu/Info.plist
  package-lock.json
  package.json
Labels: enhancement

#206 로그인 로직 변경 대응
  src/apis/UserApi.ts
  src/screens/SignUp/index.tsx
  src/store/userSlice/index.ts
Labels: refactorize

#208 React query/#207
  App.tsx
  package-lock.json
  package.json
  src/queryKeys/index.ts
  src/store/userSlice/index.ts
Labels: enhancement

#212 User/#211
  App.tsx
  package-lock.json
  package.json
  src/apis/BaseInstance.ts
  src/apis/UserApi.ts
  src/constants/asyncStorage.ts
  src/helpers/functions/validate.ts
  src/queryKeys/index.ts
  src/queryKeys/user.ts
  src/screens/Login/index.tsx
  src/screens/Profile/Logged/Force.tsx
  src/screens/Profile/Logged/Information.tsx
  src/screens/Profile/Logged/index.tsx
  src/screens/Profile/index.tsx
  src/screens/ProfileModify/index.tsx
  src/screens/SignUp/Check.tsx
  src/screens/SignUp/Input.tsx
  src/screens/SignUp/index.tsx
  src/store/userSlice/index.ts
  src/store/userSlice/userSlice.ts
  src/types/user.ts
Labels: refactorize, sprint
