Repository wafflestudio/gatgu-client, pull requests merged in 2021-06, with the labels that each got.

#224 글쓰기 + 글 상세 보기 new API에 맞게 수정
  fake-server/db.json
  src/apis/ArticleApi.ts
  src/components/WriteArticle/Recruiting/Recruiting.tsx
  src/components/WriteArticle/index.tsx
  src/constants/Enum.ts
  src/constants/InitialState.ts
  src/screens/Article/Chat.tsx
  src/screens/Article/GoalTopBubble/TopBubble/index.tsx
  src/screens/Article/GoalTopBubble/index.tsx
  src/screens/Article/Info.tsx
  src/screens/Article/ProductImages.tsx
  src/screens/Article/ProfileChat.tsx
  src/screens/Article/Title.tsx
  src/screens/Article/TitleInfo.tsx
  src/screens/Article/index.tsx
  src/screens/Drawer/index.tsx
  src/store/articleSlice/index.ts
  src/types/article.ts
  src/types/chat.ts
Labels: sprint

#223 FCM Configuration
  App.tsx
  package-lock.json
  package.json
  src/constants/asyncStorage.ts
  src/helpers/GatguNotification/Context.ts
  src/helpers/GatguNotification/Provider.tsx
  src/helpers/GatguNotification/index.ts
  src/helpers/functions/asyncStorage.ts
  src/types/Notification.ts
Labels: enhancement

#236 Sprint/reboot sp1 #203
  App.tsx
  fake-server/db.json
  package-lock.json
  package.json
  src/apis/ArticleApi.ts
  src/apis/BaseInstance.ts
  src/apis/UserApi.ts
  src/apis/gatguAxios.ts
  src/components/WriteArticle/DueDate/DueDate.style.ts
  src/components/WriteArticle/DueDate/DueDate.tsx
  src/components/WriteArticle/Recruiting/Recruiting.tsx
  src/components/WriteArticle/index.tsx
  src/constants/Enum.ts
  src/constants/InitialState.ts
  src/constants/asyncStorage.ts
  src/helpers/functions/asyncStorage.ts
  src/helpers/functions/validate.ts
  src/queryKeys/index.ts
  src/queryKeys/user.ts
  src/screens/Article/Chat.tsx
  src/screens/Article/GoalTopBubble/TopBubble/index.tsx
  src/screens/Article/GoalTopBubble/index.tsx
  src/screens/Article/Info.tsx
  src/screens/Article/ProductImages.tsx
  src/screens/Article/ProfileChat.tsx
  src/screens/Article/Title.tsx
  src/screens/Article/TitleInfo.tsx
  src/screens/Article/index.tsx
  src/screens/Drawer/index.tsx
  src/screens/Login/index.tsx
  src/screens/Profile/Logged/Force.tsx
  src/screens/Profile/Logged/Information.tsx
  src/screens/Profile/Logged/index.tsx
  src/screens/Profile/index.tsx
  src/screens/ProfileModify/index.tsx
  src/screens/SignUp/Check.tsx
  src/screens/SignUp/Input.tsx
  src/screens/SignUp/index.tsx
  src/screens/StackScreens.tsx
  src/store/articleSlice/index.ts
  src/store/userSlice/index.ts
  src/store/userSlice/userSlice.ts
  src/types/article.ts
  src/types/chat.ts
  src/types/user.ts
Labels: sprint

#239 Fix/#238
  App.tsx
  src/apis/ArticleApi.ts
Labels: hotfix

#215 유저 정보 수정
  src/apis/UserApi.ts
  src/apis/gatguAxios.ts
  src/queryKeys/user.ts
  src/screens/Profile/Profile.style.ts
  src/screens/Profile/index.tsx
  src/screens/ProfileModify/ProfileModify.styles.ts
  src/screens/ProfileModify/index.tsx
  src/screens/StackScreens.tsx
Labels: sprint

#243 User gatgu/#230
  ios/Podfile.lock
  package-lock.json
  src/apis/ArticleApi.ts
  src/components/ArticleBox/index.tsx
  src/enums/index.ts
  src/enums/userArticleActivity.ts
  src/helpers/GatguNotification/Provider.tsx
  src/helpers/routes.tsx
  src/screens/Profile/Logged/HistoryList.tsx
  src/screens/StackScreens.tsx
  src/screens/UserGatgu/UserGatgu.tsx
  src/screens/UserGatgu/UserGatguList.tsx
  src/screens/UserGatgu/index.ts
  src/types/article.ts
Labels: enhancement, sprint

#235 api Testing for article read, write, edit (no image)
  .gitignore
  ios/Podfile.lock
  ios/gatgu.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  package-lock.json
  package.json
  src/apis/ArticleApi.ts
  src/apis/UserApi.ts
  src/assets/images/no-image.png
  src/components/ArticleBox/index.tsx
  src/components/ArticleListTemplate/index.tsx
  src/components/WriteArticle/DueDate/DueDate.tsx
  src/components/WriteArticle/Recruiting/Recruiting.tsx
  src/components/WriteArticle/Tags/Tags.tsx
  src/components/WriteArticle/index.tsx
  src/constants/Enum.ts
  src/constants/InitialState.ts
  src/enums/articleStatus.ts
  src/enums/orderStatus.ts
  src/helpers/functions/time.ts
  src/screens/Article/Chat.tsx
  src/screens/Article/Desc.style.ts
  src/screens/Article/Desc.tsx
  src/screens/Article/GoalTopBubble/TopBubble/index.tsx
  src/screens/Article/GoalTopBubble/index.tsx
  src/screens/Article/Info.tsx
  src/screens/Article/ProductImages.style.ts
  src/screens/Article/ProductImages.tsx
  src/screens/Article/ProfileChat.tsx
  src/screens/Article/Title.tsx
  src/screens/Article/TitleInfo.tsx
  src/screens/Article/index.tsx
  src/screens/Drawer/index.tsx
  src/types/article.ts
  src/types/chat.ts
  src/types/shared.ts
Labels: sprint

#251 asset 파일구조 고치기
  app.json
  ios/Podfile.lock
  src/assets/BottomTabIndex.ts
  src/assets/Icon/index.ts
  src/assets/icons/BackIcon/BackIcon.svg
  src/assets/icons/Chat/chat.svg
  src/assets/icons/ChatDark/chatDark.svg
  src/assets/icons/CrossSign/XSign.svg
  src/assets/icons/CrossSign/index.tsx
  src/assets/icons/Etc/etc.svg
  src/assets/icons/EtcDark/etcDark.svg
  src/assets/icons/GradeBar/GradeBar.svg
  src/assets/icons/Home/home.svg
  src/assets/icons/HomeDark/homeDark.svg
  src/assets/icons/Logo/Logo13.svg
  src/assets/icons/Logo/Logo15.svg
  src/assets/icons/Logo/index.ts
  src/assets/icons/MainLogo/Logo13.svg
  src/assets/icons/MainLogo/index.ts
  src/assets/icons/ModifyButton/modifyButton.svg
  src/assets/icons/Notification/notification.svg
  src/assets/icons/Open/open.svg
  src/assets/icons/Participate/participate.svg
  src/assets/icons/PlusSign/index.ts
  src/assets/icons/PlusSign/plusSign.svg
  src/assets/icons/ProfileDummyImage/ProfileDummyImage.svg
  src/assets/icons/Search/search.svg
  src/assets/icons/SearchDark/searchDark.svg
  src/assets/icons/SubLogo/Logo15.svg
  src/assets/icons/SubLogo/index.ts
  src/assets/icons/Write/write.svg
  src/assets/icons/WriteDark/writeDark.svg
  src/assets/images/BackIcon.png
  src/assets/images/ProfileDummyImage.png
  src/assets/images/ProfilePageImage1.png
  src/assets/images/ProfilePageImage2.png
  src/assets/images/icon.png
  src/assets/images/splash.png
  src/components/BottomNavigation/index.tsx
  src/components/HDRBackBtn/index.tsx
  src/components/WriteArticle/AddImage/AddImage.tsx
  src/screens/AppLoading/index.tsx
  src/screens/Login/index.tsx
  src/screens/Profile/Logged/Force.tsx
  src/screens/Profile/Logged/Grade.tsx
  src/screens/Profile/Logged/Information.tsx
  src/screens/Profile/UnLogged/index.tsx
  src/screens/ProfileModify/index.tsx
  src/screens/StackScreens.tsx
Labels: refactorize, sprint
